# For all available configuration settings, please go to:
#   https://docs.viktor.ai/docs/create-apps/references/viktor-config-toml

app_type = 'simple'
# assets_path = 'assets'
python_version = '3.10'  # '3.8' | '3.9' | '3.10' | '3.11'
# welcome_text = 'welcome.md'
